// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A grocery item categorization AI agent.
 *
 * - categorizeItems - A function that handles the grocery item categorization process.
 * - CategorizeItemsInput - The input type for the categorizeItems function.
 * - CategorizeItemsOutput - The return type for the categorizeItems function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CategorizeItemsInputSchema = z.object({
  items: z
    .string()
    .describe('A comma separated list of grocery items to categorize.'),
});
export type CategorizeItemsInput = z.infer<typeof CategorizeItemsInputSchema>;

const CategorizeItemsOutputSchema = z.record(z.string(), z.array(z.string())).describe('A record of aisles and the items in them.');

export type CategorizeItemsOutput = z.infer<typeof CategorizeItemsOutputSchema>;

export async function categorizeItems(input: CategorizeItemsInput): Promise<CategorizeItemsOutput> {
  return categorizeItemsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'categorizeItemsPrompt',
  input: {schema: CategorizeItemsInputSchema},
  output: {schema: CategorizeItemsOutputSchema},
  prompt: `You are a grocery shopping expert. You will categorize a list of grocery items into supermarket aisles.

  Return a JSON object where the keys are the aisles, and the values are arrays of grocery items that belong in that aisle.
  Example:
  {
    "Produce": ["apples", "bananas", "carrots"],
    "Dairy": ["milk", "cheese", "yogurt"]
  }

  Items: {{{items}}}
  `,
});

const categorizeItemsFlow = ai.defineFlow(
  {
    name: 'categorizeItemsFlow',
    inputSchema: CategorizeItemsInputSchema,
    outputSchema: CategorizeItemsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
