name: Deploy to Cloud Run

# Run this workflow on every push to the main branch
on:
  push:
    branches: [ main ]

# Set environment variables
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: aislepilot-api
  REGION: us-central1

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Docker Image
        run: |-
          gcloud builds submit --tag "us-central1-docker.pkg.dev/${PROJECT_ID}/aislepilot-repo/${SERVICE_NAME}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image "us-central1-docker.pkg.dev/${PROJECT_ID}/aislepilot-repo/${SERVICE_NAME}:${{ github.sha }}" \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}"
